package ClassTasks;

import java.util.*;

public class T18_UserNameGenerator {

    public static void main(String[] args) {

        // write the main method logic here

        Scanner scanner = new Scanner(System.in);

        System.out.print("Enter your first name: ");
        String firstName = scanner.nextLine();

        System.out.print("Enter your last name: ");
        String lastName = scanner.nextLine();

        generateUsername(firstName, lastName);
    }

    public static void generateUsername(String firstName, String lastName){

        //implement the method here

        String first = firstName.toLowerCase();
        String last = lastName.toLowerCase();

        int num1 = (int)(Math.random()*9 + 0);
        int num2 = (int)(Math.random()*9 + 0);
        int num3 = (int)(Math.random()*9 + 0);

        String userName;

        if (first.length() < 3 || last.length() < 3) {
            userName = first + "_" + last + num1 + num2 + num3;

        } else {
            String first3 = first.substring(0, 3);
            String lastHalf = last.substring(last.length() / 2 - 1);
            String last3 = lastHalf.substring(lastHalf.length() - 3);
            userName = first3 + "_" + last3 + num1 + num2 + num3;
        }

        System.out.println(userName);

    }

}
/**
 *Username Generator for a Social Media Platform
 *
 * When new users join a social media platform, the platform often suggests available usernames based on the user's real name if their chosen username is already taken. This suggestion is often generated by manipulating their real name and adding some numbers or symbols to it.
 *
 * Objective:
 * Create a Username Generator tool that takes a user's first name and last name, and produces a suggested username by combining parts of their name and adding some predefined symbols or numbers.
 *
 * Steps:
 * 1. Create a method called generateUsername(String firstName, String lastName).
 *
 *  In the method utilize string methods to:
 *
 *   - Convert both names to lowercase.
 *   - Extract the first three letters of the firstName and the last three letters of the lastName.
 *   - Concatenate the extracted letters with a predefined symbol (e.g., "_") in between.
 *   - Append a random 3 digit number (e.g., "007") to the end of the generated string to make the username unique.
 *
 * 2. In the main method:
 *
 *   - Prompt the user to enter their first and last name.
 *   - Call the generateUsername method with the user's input and display the suggested username.
 *
 * Example:
 *
 * Enter your first name: James
 * Enter your last name: Bond
 *
 * Suggested Username: jam_ond007
 *
 *
 * BONUS: Add a check for the length of the string. If either the first or last name is less than 3 characters, simply concatenate them and add the random number
 *
 * Example:
 *
 * Enter your first name: Yi
 * Enter your last name: Oh
 *
 * Suggested Username: yi_oh931
 */
